version: "0.2"
language: "en-US"
words:
  - andreas
  - commitlint
  - remigius
  - virtualenv
ignorePaths:
  - .git
  - .claude/
  - "**/.cspell.yaml"
dictionaries: []
dictionaryDefinitions: []
import: []
